name: sf-mvp
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.4
  - mkl=2023.*
  - intel-openmp=2023.*
  - numpy
  - pyyaml
  - pip
  - pip:
    - transformers
    - peft
    - sentence-transformers
    - spacy
    - networkx
    - usearch
